'use client';
import { motion } from 'framer-motion';
import { Menu, Phone, Star, Zap } from 'lucide-react';
import Image from 'next/image';
import { useState } from 'react';
import { siteConfig } from '@/siteConfig';

const imgs=['hero.jpg','switchboardafter.jpg','lightinstall.jpg','switchboardfinished.jpg','outdoorkitchenandspa.jpg','switchboardbefore.jpg','logo.jpg'];
const vids=['mirror.mp4','pendant.mp4'];

export default function HomePage(){const [open,setOpen]=useState(false);return <main className='relative z-10'>
<header className='sticky top-0 z-50 backdrop-blur bg-black/50 border-b border-yellow-400/20'><nav className='max-w-6xl mx-auto p-4 flex justify-between items-center'><span className='font-display text-3xl tracking-wider'>SM <span className='text-spark'>Electrical</span></span><button className='md:hidden' onClick={()=>setOpen(!open)}><Menu/></button><div className='hidden md:flex gap-6 items-center text-sm'><a href='#services'>Services</a><a href='#reviews'>Reviews</a><a href='#quote' className='px-4 py-2 rounded-full bg-spark text-black font-semibold shadow-[0_0_24px_rgba(250,204,21,.45)]'>Call Sam</a></div></nav>{open&&<div className='md:hidden p-4 flex flex-col gap-3'><a href='#services'>Services</a><a href='#reviews'>Reviews</a></div>}</header>
<section className='min-h-[92vh] relative flex items-center'><Image src='/images/hero.jpg' alt='' fill className='object-cover'/><div className='absolute inset-0 bg-black/70'/><div className='max-w-6xl mx-auto px-4 relative'><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} className='font-display text-6xl md:text-8xl leading-none max-w-4xl'>Perth's Electrician. <span className='text-spark underline decoration-4 decoration-spark'>No Robots.</span> No Runaround.</motion.h1><p className='mt-4 max-w-xl text-lg'>Owner-operated. Fully licensed. Free quotes. Sam answers the phone and does the work.</p><div className='mt-8 flex gap-4'><a href='#quote' className='bg-spark text-black px-6 py-3 rounded-full font-bold shadow-[0_0_24px_rgba(250,204,21,.55)]'>Get a Free Quote</a><a href='tel:0427771905' className='px-6 py-3 border border-white/40 rounded-full'>Call Sam — 0427 771 905</a></div></div></section>
<section className='grid grid-cols-2 md:grid-cols-4 gap-4 max-w-6xl mx-auto px-4 py-8 text-center'>{['8+ Five Star Reviews','100% Residential Focus','Perth Local','Direct Line to Sam'].map(t=><motion.div key={t} whileInView={{opacity:[0,1],y:[10,0]}} className='bg-zinc-900 p-4 rounded-lg border border-spark/20'>{t}</motion.div>)}</section>
<section className='max-w-6xl mx-auto px-4 py-16 grid md:grid-cols-2 gap-10 items-center'><Image src='/images/switchboardfinished.jpg' alt='Sam work' width={900} height={700} className='rounded-xl'/><div><h2 className='font-display text-5xl'>About Sam</h2><p className='mt-4 text-zinc-300'>We're not the biggest company (probably the smallest) — but at SM Electrical, we keep things simple: quality work, reliability, and direct contact without talking to a robot.</p><p className='mt-4'>Sam keeps it straightforward: good communication, tidy work, and no runaround.</p></div></section>
<section id='services' className='max-w-6xl mx-auto px-4 py-16'><h2 className='font-display text-5xl mb-8'>Residential Services</h2><div className='grid md:grid-cols-4 gap-4'>{siteConfig.services.map((s,i)=><motion.div key={s} whileHover={{y:-6}} className='rounded-xl overflow-hidden border border-spark/20 shadow-[0_0_20px_rgba(250,204,21,0.08)] relative'><Image src={`/images/${imgs[i%imgs.length]}`} alt={s} width={600} height={420} className='h-52 object-cover'/><div className='p-4 bg-zinc-950'><Zap className='text-spark w-5 h-5 mb-2'/><h3 className='font-bold'>{s}</h3><p className='text-sm text-zinc-400'>Installed with care by Sam, built to last.</p></div></motion.div>)}</div></section>
<section id='reviews' className='max-w-6xl mx-auto px-4 py-16'><h2 className='font-display text-5xl mb-8'>Client Reviews</h2><div className='grid md:grid-cols-2 gap-4'>{siteConfig.reviews.map(([n,r])=><motion.blockquote key={n} whileInView={{opacity:[0,1],y:[20,0]}} className='bg-zinc-900 rounded-xl p-6 border border-spark/20'><div className='text-spark text-4xl'>“</div><p>{r}</p><div className='mt-4 font-bold'>{n}</div><div className='flex mt-1'>{[...Array(5)].map((_,i)=><Star key={i} className='w-4 h-4 fill-spark text-spark'/>)}</div></motion.blockquote>)}</div></section>
<section className='max-w-6xl mx-auto px-4 py-16'><div className='grid md:grid-cols-2 gap-4 mb-4'>{vids.map(v=><video key={v} src={`/videos/${v}`} autoPlay loop muted playsInline className='rounded-xl w-full h-64 object-cover'/>)}</div><div className='columns-1 md:columns-3 gap-4 space-y-4'>{imgs.map(i=><div key={i} className='break-inside-avoid overflow-hidden rounded-xl'><Image src={`/images/${i}`} alt={i} width={700} height={520} className='hover:scale-105 transition duration-500'/></div>)}</div></section>
<section id='quote' className='bg-zinc-950 py-16'><form action='/api/quote' method='post' className='max-w-4xl mx-auto px-4 grid md:grid-cols-2 gap-4'><h2 className='md:col-span-2 font-display text-5xl'>Get a Free Quote from Sam</h2>{['Name','Phone','Email','Suburb'].map(f=><input key={f} name={f.toLowerCase()} placeholder={f} required className='bg-black border border-zinc-700 rounded-lg p-3'/>) }<select name='service' className='bg-black border border-zinc-700 rounded-lg p-3'>{siteConfig.services.map(s=><option key={s}>{s}</option>)}</select><div/><textarea name='message' placeholder='Message' className='md:col-span-2 min-h-32 bg-black border border-zinc-700 rounded-lg p-3'/><button className='md:col-span-2 bg-spark text-black font-bold py-3 rounded-lg shadow-[0_0_24px_rgba(250,204,21,.55)]'>Get a Free Quote from Sam</button></form></section>
<footer className='border-t border-spark/20 py-10 text-center text-zinc-400'><p className='font-display text-3xl text-white'>SM Electrical WA</p><p>Quality work. No robots.</p><p className='mt-2'>{siteConfig.phone} · {siteConfig.email} · Perth WA</p><p className='text-xs mt-2'>Website by Built for Perth</p><Phone className='mx-auto mt-2 text-spark'/></footer>
</main>}
